### Variables 
@baseUrl = http://localhost:5000/api
@adminToken = Halkan_Geli_Token_ka_Admin_ka
@userId = 695e8f6e186dfcd019a4b938

### 1. REGISTER ADMIN (Tijaabada koowaad)
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Admin Ibra",
    "email": "admin@gmail.com",
    "password": "Password123",
    "role": "admin"
}

### 2. LOGIN (Si aad u hesho Token-ka)
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Password123"
}

### 3. GET ALL USERS (Cadaynta Amniga)
# Tijaabi inuu soo celiyo dhammaan dadka
GET {{baseUrl}}/users/getUsers
Authorization: Bearer {{adminToken}}

### 4. UPDATE USER (Tijaabada Model Hook-ga)
# Waxaan tijaabinaynaa inuu password-ka cusub hash gareeyo
PUT {{baseUrl}}/users/updateUser/{{userId}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "email": "ibra@gmail.com",
    "password": "Password123"
}

### 5. DELETE USER (Tijaabada ugu dambaysa)
DELETE {{baseUrl}}/users/deleteUser/{{userId}}
Authorization: Bearer {{adminToken}}