### Variables 
@baseUrl = http://localhost:5000/api
@serviceId = 69639a95d9878ddcc752e8e0
###  login to get  token 

# @name login

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "Password123"
}
###
@authToken = {{login.response.body.user.token}}
@userId = {{login.response.body.user.id}}

### 1. CREATE BOOKING (User-ku waa inuu Login yahay)
# Tijaabadani waxay xisaabin doontaa totalPrice waxayna xiri doontaa qolka
POST {{baseUrl}}/booking/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "user": "{{userId}}",
    "service": "{{serviceId}}",
    "checkInDate": "2026-02-01",
    "checkOutDate": "2026-02-05",
    "status": "confirmed"
}

### 2. TEST DOUBLE BOOKING (Amniga Logic-ga)
# Mar kale isku day qolkaas adigoo isticmaalaya xogta kore.
# Waa inay kuu diidaa: "Adeeggan horay ayaa loo qabsaday!"
POST {{baseUrl}}/booking/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "user": "{{userId}}",
    "service": "{{serviceId}}",
    "checkInDate": "2026-02-10",
    "checkOutDate": "2026-02-12"
}

### 3. GET ALL BOOKINGS (Admin Only)
GET {{baseUrl}}/bookings/getbooking
Authorization: Bearer {{authToken}}

### 4. DELETE/CANCEL BOOKING
# Tani waxay tirtiri doontaa booking-ka, qolkana waxay ka dhigi doontaa "Available"
DELETE {{baseUrl}}/bookings/delete/{{bookingId}}
Authorization: Bearer {{authToken}}