### Variables 
@baseUrl = http://localhost:5000/api
@serviceID = 696399cff23a0c2a0b95c9a8


###  login to get  token 

# @name login

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Password123"
}
###
@authToken = {{login.response.body.user.token}}


### 1. CREATE SERVICE (Kaliya Admin)
POST {{baseUrl}}/services/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "serviceName": "Luxury Suite 101",
    "category": "Room",
    "type": "King Size",
    "price": 150,
    "description": "A beautiful luxury room with a sea view and free breakfast."
}

### 2. GET ALL SERVICES (Login User)
GET {{baseUrl}}/services/getservice
Authorization: Bearer {{authToken}}

### 3. GET SINGLE SERVICE
GET {{baseUrl}}/services/getservice/{{serviceID}}
Authorization: Bearer {{authToken}}

### 4. UPDATE SERVICE (Admin Kaliya)
PUT {{baseUrl}}/services/update/{{serviceID}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "price": 175,
    "isAvailable": false
}

### 5. DELETE SERVICE (Admin Kaliya)
DELETE {{baseUrl}}/services/delete/{{serviceID}}
Authorization: Bearer {{authToken}}